BOARDCPPSRC =  $(BOARD_DIR)/board_configuration.cpp

SHORT_BOARD_NAME=zgrywus-ms43
DDEFS += -DFIRMWARE_ID=\"zgrywus-ms43\"
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::F15
DDEFS += -DRAM_UNUSED_SIZE=1000
DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE
DDEFS += -DEFI_AUX_SERIAL=FALSE
DDEFS += -DEFI_MAX_31855=TRUE
