BOARDCPPSRC =  $(BOARD_DIR)/board_configuration.cpp

IS_STM32F429 = yes
SHORT_BOARD_NAME=zgrywus-k12
DDEFS += -DFIRMWARE_ID=\"zgrywus-k12\"
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::F15
DDEFS += -DRAM_UNUSED_SIZE=1000
DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE
DDEFS += -DEFI_AUX_SERIAL=FALSE
DDEFS += -DEFI_MAX_31855=TRUE
DDEFS += -DSTM32_SPI_USE_SPI1=FALSE
DDEFS += -DSTM32_SPI_USE_SPI2=FALSE
DDEFS += -DSTM32_SPI_USE_SPI3=TRUE
DDEFS += -DSTM32_SPI_USE_SPI4=TRUE
DDEFS += -DSTM32_SPI_USE_SPI5=FALSE
DDEFS += -DSTM32_SPI_USE_SPI6=FALSE
